version: '3'
services:
  nodered:
    image: nodered/node-red
    container_name: nodered
    restart: unless-stopped
    labels:
      - "traefik.http.routers.nodered.entrypoints=websecure"
      - "traefik.http.routers.nodered.rule=Host(`nodered.${APPDOMAIN:-local}`)"
      - "traefik.http.services.nodered.loadbalancer.server.port=1880"
      - "traefik.http.routers.nodered.middlewares=auth"
#      - "traefik.http.middlewares.auth.basicauth.users=mikkorauhala:$$apr1$$Yj9Ud8Dc$$6KeZVZktED3bfMnq2BnUA."
    environment:
      - TZ=Europe/Helsinki
    volumes:
      - nodered-storage:/data
      - bufr-storage:/bufr
    networks:
      - traefik-network

volumes:
  nodered-storage:
  bufr-storage:

networks:
    traefik-network:
      external: true
